[ssi-bad-debt] 14.0.1.0.0
open-synergy/ssi-bad-debt pull request #1
Opened 2023-01-22 09:06 UTC by usa8bit

2023-01-24 09:10 UTC, mikevhe18 requested changes

2023-01-24 09:10 UTC, mikevhe18 commented on ssi-bad-debt/README.rst
> +===============
Garisnya samakan dengan panjang labelnya

2023-01-24 09:10 UTC, mikevhe18 commented on ssi-bad-debt/README.rst
> +5.  Search For *Cost Accounting*
Search For Bad Debt

2023-01-24 09:10 UTC, mikevhe18 commented on ssi-bad-debt/__manifest__.py
> +    "category": "Uncategorize",
Accounting

2023-01-24 09:10 UTC, mikevhe18 commented on ssi-bad-debt/data/approval_template_data.xml
> +     License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl). -->
Sesuaikan tahunnya menjadi 2023

2023-01-24 09:10 UTC, mikevhe18 commented on ssi-bad-debt/security/res_group_data.xml
> +     License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl). -->
Sesuaikan tahunnya menjadi 2023

2023-01-24 09:10 UTC, mikevhe18 commented on ssi-bad-debt/security/ir_rule_data.xml
> +     License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl). -->
Sesuaikan tahunnya menjadi 2023

2023-01-24 09:10 UTC, mikevhe18 commented on ssi-bad-debt/security/ir_module_category_data.xml
> +     License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl). -->
Sesuaikan tahunnya menjadi 2023

2023-01-24 09:10 UTC, mikevhe18 commented on ssi-bad-debt/models/bad_debt_direct_write_off.py
> +    @api.multi
@api.multi dihapus
karena di versi 14.0 tidak perlu lagi dituliskan

2023-01-24 09:10 UTC, mikevhe18 commented on ssi-bad-debt/models/__init__.py
> +from . import bad_debt_direct_write_off_type
apabila perlu import lebih dari 1 file python, maka penulisannya:
```
from . import (
    file_python_1,
    file_python_2,
    ...,
    dst,
)
```

2023-01-24 09:10 UTC, mikevhe18 commented on ssi-bad-debt/models/bad_debt_direct_write_off.py
> +        ]
Sesuaikan value dengan type fieldnya, jgn gunakan string
```
return [
    ("partner_id", "=", self.partner_id.id),
    ("day_due", ">=", self.type_id.min_days_due),
    ("day_due", "<=", self.type_id.max_date_due),
    ("full_reconcile_id", "=", False),
    ("account_id", "in", self.type_id.allowed_account_ids.ids),
]
```

2023-01-24 09:10 UTC, mikevhe18 commented on ssi-bad-debt/models/bad_debt_direct_write_off.py
> +        return {"bad_debt_id": self.id, "source_move_line_id": move_line.id}
```
def _prepare_detail_data(self, move_line_id):
    self.ensure_one()
    return {"bad_debt_id": self.id, "source_move_line_id": move_line_id}
```

2023-01-24 09:10 UTC, mikevhe18 commented on ssi-bad-debt/models/bad_debt_direct_write_off.py
> +            return True
```
if self.move_id:
    self.move_id.unlink()
```

2023-01-24 09:10 UTC, mikevhe18 commented on ssi-bad-debt/models/bad_debt_direct_write_off.py
> +            obj_account_move = self.env["account.move"]
Tambahkan context check_move_validity = False
`obj_move = self.env["account.move"].with_context(check_move_validity=False)`

2023-01-24 09:11 UTC, mikevhe18 commented
@usa8bit Jangan lupa untuk setiap file tambahkan juga licensenya. Link dokumentasi: https://ssi.simetri-sinergi.id/slides/slide/license-268

2023-01-24 09:13 UTC, mikevhe18 commented
@usa8bit kemudian gunakan decorator untuk _create_accounting_entry dan _delete_accounting_entry. Link Dokumentasi: https://www.youtube.com/watch?v=jioNWG50toc

2023-01-26 00:51 UTC, mikevhe18 requested changes

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/models/bad_debt_direct_write_off_detail.py
> +        comodel_name="detail_ids",
comodel_name="bad.debt.direct.write.off"

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/models/bad_debt_direct_write_off_detail.py
> +        comodel_name="account_move_line",
comodel_name="account.move.line"

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/models/bad_debt_direct_write_off_detail.py
> +    )
related="source_move_line_id.date_maturity"

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/models/bad_debt_direct_write_off_detail.py
> +        string="Day Due", related="source_move_line_id.day_due", store=True
related="source_move_line_id.days_overdue"

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/models/bad_debt_direct_write_off_type.py
> +    allowed_account_ids = fields.Many2many()
```
    allowed_account_ids = fields.Many2many(
        string="Allowed Accounts",
        comodel_name="account.account",
        relation="rel_bad_debt_type_2_account",
        column1="type_id",
        column2="account_id",
    )
```

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/security/ir.model.access.csv
> +
Untuk security ir.model.access.csv tidak perlu ada license. Dihapus saja

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/data/approval_template_data.xml
> +                eval="[(6,0,[ref('bad_debt_validator_group')])]"
eval="[(6,0,[ref('bad_debt_direct_write_off_validator_group')])]"

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/data/policy_template_data.xml
> +            <field name="group_ids" eval="[(6,0,[ref('bad_debt_user_group')])]" />
bad_debt_direct_write_off_user_group

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/data/policy_template_data.xml
> +            <field name="group_ids" eval="[(6,0,[ref('bad_debt_validator_group')])]" />
bad_debt_direct_write_off_validator_group

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/data/policy_template_data.xml
> +            <field name="group_ids" eval="[(6,0,[ref('bad_debt_validator_group')])]" />
bad_debt_direct_write_off_validator_group

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/data/policy_template_data.xml
> +            <field name="group_ids" eval="[(6,0,[ref('bad_debt_user_group')])]" />
bad_debt_direct_write_off_user_group

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/data/policy_template_data.xml
> +            <field name="group_ids" eval="[(6,0,[ref('bad_debt_validator_group')])]" />
bad_debt_direct_write_off_validator_group

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/views/bad_debt_direct_write_off_view.xml
> +            ref="ssi_master_data_mixin.mixin_master_data_view_tree"
ref="ssi_transaction_mixin.mixin_transaction_view_tree"

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/views/bad_debt_direct_write_off_view.xml
> +            </field>
```
<xpath expr="//field[@name='user_id']" position="after">
    <field name="partner_id" widget="many2one_avatar" />
    <field name="type_id" />
    <field name="date" />
</xpath>
```

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/views/bad_debt_direct_write_off_view.xml
> +            ref="ssi_master_data_mixin.mixin_master_data_view_form"
ref="ssi_transaction_mixin.mixin_transaction_view_form"

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/views/bad_debt_direct_write_off_view.xml
> +    <record id="action_bad_debt" model="ir.actions.act_window">
id="bad_debt_direct_write_off_action"

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/views/bad_debt_direct_write_off_view.xml
> +    </record>
Tambakan menu dibawah action
```
    <menuitem
        id="bad_debt_direct_write_off_menu"
        name="Bad Debt"
        parent="menu_bad_debt"
        groups="bad_debt_direct_write_off_viewer_group"
        action="bad_debt_direct_write_off_action"
        sequence="1"
    />
```

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/menu.xml
> +    </record>
Dihapus

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/menu.xml
> +    />
Dihapus

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/menu.xml
> +    />
Dihapus

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/menu.xml
> +        parent="menu_financial_accounting_configuration"
parent="ssi_financial_accounting.menu_financial_accounting_configuration"

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/menu.xml
> +        parent="menu_root_financial_accounting"
parent="ssi_financial_accounting.menu_root_financial_accounting"

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/models/bad_debt_direct_write_off.py
> +        string="# Type",
string="Type"

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/models/bad_debt_direct_write_off.py
> +        string="# Partner",
string="Partner"

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/models/bad_debt_direct_write_off.py
> +        string="# Journal",
string="Journal"

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/models/bad_debt_direct_write_off.py
> +        string="# Expense Account",
string="Expense Account"

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/models/bad_debt_direct_write_off.py
> +        string="# Detail",
string="Details"

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/models/bad_debt_direct_write_off_type.py
> +        string="# Journal", comodel_name="account.journal", ondelete="restrict"
string="Journal"

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/models/bad_debt_direct_write_off_type.py
> +        string="# Expense Account", comodel_name="account.account", ondelete="restrict"
string="Expense Account"

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/views/bad_debt_direct_write_off_view.xml
> +            </group>
```
<xpath expr="//field[@name='user_id']" position="after">
    <field name="partner_id"/>
    <field name="type_id" />
    <field name="company_currency_id" />
</xpath>
<xpath expr="//group[@name='header_right']" position="inside">
    <field name="date" />
</xpath>
<xpath expr="//page[@name='note']" position="before">
    <page name="page_detail" string="Details">
        <field name="detail_ids" />
    </page>
</xpath>
```

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/models/bad_debt_direct_write_off_detail.py
> +                self.source_move_line_id.amount_residual_currency.id
tidak perlu menggunakan "id"
```
self.amount_residual_currency = (
    self.source_move_line_id.amount_residual_currency
)
```

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/models/bad_debt_direct_write_off_detail.py
> +            self.amount_residual = self.source_move_line_id.amount_residual.id
tidak perlu menggunakan "id"
`self.amount_residual = self.source_move_line_id.amount_residual`

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/models/bad_debt_direct_write_off.py
> +
Tambahkan:
```
# Attributes related to add element on view automatically
_automatically_insert_view_element = True
_automatically_insert_multiple_approval_page = True
_automatically_insert_done_button = False
_automatically_insert_done_policy_fields = False
```

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/models/bad_debt_direct_write_off_detail.py
> +    )
tambahkan Field:
```
company_currency_id = fields.Many2one(
    string="Company Currency",
    related="source_move_line_id.company_currency_id"
)
```

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/models/bad_debt_direct_write_off_detail.py
> +    amount = fields.Monetary(string="Amount", related="source_move_line_id.balance")
Tambahkan attribute
`currency_field="company_currency_id",`

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/models/bad_debt_direct_write_off_detail.py
> +    )
Tambahkan attribute
`currency_field="company_currency_id",`

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/models/bad_debt_direct_write_off_detail.py
> +    amount_residual = fields.Monetary(string="Amount Residual", readonly=True)
Tambahkan attribute
`currency_field="company_currency_id",`

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/models/bad_debt_direct_write_off_detail.py
> +    )
Tambahkan attribute
`currency_field="company_currency_id",`

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/views/bad_debt_direct_write_off_detail_view.xml
> +            <tree>
<tree editable="bottom">

2023-01-26 00:51 UTC, mikevhe18 commented on ssi-bad-debt/views/bad_debt_direct_write_off_detail_view.xml
> +    </record>
Tidak perlu ada form. Dihapus saja

2023-01-26 00:54 UTC, mikevhe18 commented
@usa8bit Tambahkan folder static dengan icon. Contoh bisa dilihat di modul hr_reimbursement. [LINK](https://github.com/open-synergy/opnsynid-hr-expense/tree/8.0/hr_reimbursement/static/description)

2023-01-26 01:01 UTC, mikevhe18 commented
@usa8bit Tambahkan juga view untuk objek bad.debt.direct.write.off.type:
    1. Buat Search Form
        - Inherit ke ssi_master_data_mixin.mixin_master_data_view_search
    2. Buat Tree Form
        - Inherit ke ssi_master_data_mixin.mixin_master_data_view_tree
    3. Buat View Form
        - Inherit ke ssi_master_data_mixin.mixin_master_data_view_form
        - Tambahkan field berikut setelah field active:
            a. min_days_due
            b. max_days_due
        - Tambahkan page dengan field berikut sebelum page note:
            a. journal_id
            b. expense_accout_id
            c. allowed_account_ids -> widget:many2many_tags
    4. Buat Window Action
        - name: Types
    5. Buat Menu
        - name: Types
        - action: ID action pada langkah 4
        - parent: menu_bad_debt_configuration
        - groups: bad_debt_direct_write_off_type_group

2023-01-26 01:59 UTC, usa8bit commented on ssi-bad-debt/views/bad_debt_direct_write_off_view.xml
> +            </field>
yang ini amount_totalnya dihapus pak?

2023-01-28 08:20 UTC, merged